import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <header className="mb-2 shadow px-4 bg-zinc-900">
        <div className="relative max-w-5xl flex flex-col sm:flex-row mx-auto sm:items-center sm:justify-between py-4">
          <Link className="text-2xl flex items-center font-black" href="/">
            <span className="text-orange-600">Restaurante</span>
          </Link>
          <input className="peer hidden" type="checkbox" id="navbar-open" ></input>
          <label className="sm:hidden cursor-pointer absolute right-0 mt-1 text-xl" htmlFor="navbar-open" >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-6">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12H12m-8.25 5.25h16.5" />
            </svg>
          </label>
          <nav className="peer-checked:block hidden sm:block py-4 sm:mt-0">
            <ul className="flex flex-col gap-y-4 sm:flex-row sm:gap-x-8">
              <li>
                <Link className="text-gray-600 hover:text-orange-600" href="/pedidos">Pedidos</Link>
              </li>
              <li>
                <Link className="text-gray-600 hover:text-orange-600" href="/promotions">Promociones</Link>
              </li>
              <li>
                <Link className="text-gray-600 hover:text-orange-600" href="/contactos">Contactos</Link>
              </li>
              <li className="mt-2 sm:mt-0">
                <Link className="rounded-xl hover:bg-orange-600:text-white border-2 px-6 py-2 border-orange-600 font-medium text-orange-600" href="/menu">Menu</Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <body className="min-h-full flex flex-col">{children}</body>
      <footer className="fixed inset-x-0 bottom-0 p-2 text-sm flex justify-between bg-zinc-900">
        <div className="text-white">
          &copy; Restaurante. Todos los derechos reservados. 
        </div>
        <div className="space-x-3 absolute right-10">
          <a href="https://instagram.com" className="hover:underline text-white">Instagram</a>
          <a href="https://facebook.com" className="hover:underline text-white">Facebook</a>
          <a href="https://gmail.com" className="hover:underline text-white">Correo</a>
        </div>
      </footer>
    </html>
  );
}
