import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="w-full h-16 bg-zinc-950 flex items-center justify-between px-4">
          <Link href={"/"} className="text-2xl font-bold text-white">
            Restaurant
          </Link>
          <div className="flex items-center gap-4">
            <Link href={"/orders"} className="text-white hover:text-gray-400 transition-colors">
              Pedidos
            </Link>
            <Link href={"/menu"} className="text-white hover:text-gray-400 transition-colors">
              Menu
            </Link>
            <Link href={"/promotions"} className="text-white hover:text-gray-400 transition-colors">
              Promociones
            </Link>
            <Link href={"/contact"} className="text-white hover:text-gray-400 transition-colors">
              Contacto
            </Link>
          </div>
        </nav>
        {children}

      </body>
    </html>
  );
}
